# Generated by Django 3.2.7 on 2021-09-10 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='dat',
            new_name='date',
        ),
    ]
